name: Notion to Static Page

on:
  schedule:
    - cron: '0 0 * * *' # 每天深夜运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Set up Docker
    #   uses: docker/setup-buildx-action@v1

    # - name: Build Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     load: true
    #     push: false
    #     tags: my-docker-image:latest
        
    # - name: Run build.sh inside Docker container
      # run: |
      #   docker run --rm -v $(pwd):/workspace -w /workspace my-docker-image:latest https://bmpixel.notion.site/BMPixel-6f17372958844d3284524cbeea3e462c

    - name: Set up Git
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git remote set-url origin https://$GIT_USER_NAME:$GIT_PAT@github.com/${{ github.repository }}.git
      env:
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        GIT_PAT: ${{ secrets.GIT_PAT }}

    - name: Git update
      run: |
        git add .
        git commit -m "publish" || true
        git push

