name: Notion to Static Page

on:
  schedule:
    - cron: '0 0 * * *' # 每天深夜运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        load: true
        push: false
        tags: my-docker-image:latest
        
    - name: Run build.sh inside Docker container
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace my-docker-image:latest /bin/bash -c "chmod +x build.sh && ./build.sh"
